name: Yes prod CD 파이프라인

on:
  workflow_run:
    workflows: ["Yes CI 파이프라인"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-22.04
    environment: production
    permissions:
      contents: read

    steps:
      - name: Docker 이미지 Prod 배포
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.DEV_HOST}}
          username: ${{secrets.DEV_USERNAME}}
          key: ${{secrets.DEV_KEY}}
          script: |
            echo "build success"
